# Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [4]:
np.array(3)

array(3)

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1][1][:]

array([10, 11, 12])

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

The NumPy array object has a property called dtype that returns the data type of the array:

Example

In [12]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [13]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [14]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Make a copy, change the original array, and display both arrays:

In [15]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42


In [16]:
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # Or similar to x = arr 
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [18]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[31  2  3  4  5]


### NumPy Array Shape

In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
print(arr.ndim)

(2, 4)
2


In [20]:
# 1d to 2d

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# 1d to 3d

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3) 
# product of numbers in parameter should be equal to the elements in arr
# 2*2*3 = len(arr) = 12

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
newarr = arr.reshape(-1)

newarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr = arr.reshape(2,2,2)

for x in arr:
  print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [25]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [26]:
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [27]:
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# whole 2nd parth with difference of 2
for x in np.nditer(arr[:, ::2]): 
  print(x)

1
3
5
7


In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [30]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=-1)
# join 1st with 1st element
# same with 2nd

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=-1) # or axis = 1

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
# or arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Splitting Array

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [38]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


### NumPy Searching Arrays

In [40]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [42]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8)

print(x)

2


In [43]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [44]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 0, 10])

print(x)

[1 0 4]


### Sort

In [45]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [46]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [47]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [60]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [62]:
def isPrime(n) : 
 
    # Corner cases 
    if (n <= 1) : 
        return False
    if (n <= 3) : 
        return True
 
    # This is checked so that we can skip 
    # middle five numbers in below loop 
    if (n % 2 == 0 or n % 3 == 0) : 
        return False
 
    i = 5
    while(i * i <= n) : 
        if (n % i == 0 or n % (i + 2) == 0) : 
            return False
        i = i + 6
 
    return True

In [76]:
arr = np.array(range(100))

newarr = filter(isPrime,arr)

print(newarr)
print(type(newarr))

for x in newarr:
    print(x)

<class 'filter'>
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
